import Head from 'next/head';
import { useState, useRef } from 'react';

import { AiOutlineAlignLeft, AiOutlineBold, AiOutlineUnderline } from "react-icons/ai";

export default function Home() {
  const textarea = useRef();

  const [content, setContent] = useState(null);
  const [fontWeight, setFontWeight] = useState("normal");
  const [textSelected, setTextSelected] = useState(null);

  const [selectPositionStart, setSelectPositionStart] = useState(null);
  const [selectPositionEnd, setSelectPositionEnd] = useState(null);

  function getTextSelected() {
    textarea.current.addEventListener("select", (e) => {
      setTextSelected(e.target.value.substring(e.target.selectionStart, e.target.selectionEnd));
      setSelectPositionStart(e.target.selectionStart);
      setSelectPositionEnd(e.target.selectionEnd);
    });

    console.log(selectPositionStart, selectPositionEnd)
    console.log(textSelected)
  }

  return (
    <>
      <Head>
        <title>Text Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <div className='col-12 row justify-content-center align-items-center vh-100'>
          <div className="col-12">
            <p className='col-12'>{textSelected}</p>

            <div className='col-12 row gap-1 bg-dark p-2 m-0'>
              <button className='col-auto border-0'>
                <AiOutlineAlignLeft />
              </button>

              <button className='col-auto border-0' onClick={() => setFontWeight("bold")}>
                <AiOutlineBold />
              </button>

              <button className='col-auto border-0'>
                <AiOutlineUnderline />
              </button>
            </div>
            <div className='col-12'>
              <textarea
                ref={textarea}
                onSelect={getTextSelected}
                name="editor"
                rows="10"
                className='col-12 p-2 outline-0'
                onChange={(e) => setContent(e.target.value)}
                style={{ resize: "none", outline: "none", fontWeight: `${fontWeight === "bold" ? "bold" : "normal"}` }}
              >

              </textarea>
            </div>
          </div>

        </div>
      </main>
    </>
  )
}
